language: python
install:
  - pip install tox
script:
  - sudo apt-get update && sudo apt-get upgrade
  - sudo apt-get install build-essential
  - sudo apt-get install aptitude
  - sudo apt-get install libstdc++6
  - tox